### ISSUE TITLE
Armor Damaged

### ISSUE THREAD

**Issue by SpecialistNinja** [TheAz928/VanillaEnchantments#24]
Sorry if i open this case again

Armor breaking is what caused FPS lag or freezing to some certain device. Armor durability is what causing it

**Comment by inxomnyaa** [comment]
Hello mister,

thanks for open a duplicate issue.
Everything you said was already concluded and figured out in another issue that still was opened.

because of that, you just subscribed to the Annoyance™ newsletter by XenialDan

from now on you will receive one useless message with copy-pasted content per day

your subscription will run out 1 year after the last time you created a duplicated issue and can not be cancelled

Enjoy!
