### ISSUE TITLE
Item goes back to my inventory.

### ISSUE THREAD

**Issue by StupidQuestionsGuy** [TheAz928/VanillaEnchantments#58]
Hello Az, thank you so much for this plugin.

Unfortunately i'm probably making a mistake here but I've tried to enchant my wooden sword and it didn't work.

Steps:

- I got what i needed: Lapis, XP Bottles, Enchantment table and my Sword.
- When i opened the enchantment table, it gave me the normal enchantment GUI.
- When i put my sword on the weapon slot (the top one) it goes straight back to my inventory. Same for the Lapis. Both just don't accept getting in that enchantment table. 

I think this is due something i have disable or enable but i cannot find in my yml nor properties something related to enchants.

**Comment by TheAz928** [comment]
Unfortunately, this plugin doesn't enable enchantment tables yet. This is a future project. You can use enchants by doing /enchant (name or id) (level)


This plugin basically allows some plugins (like kits) to work properly because pmmp doesn't have all enchantments implemented.


NOTE: I will implement enchantment tables soon, don't worry. It's not a bug nor you're doing something wrong.
